name: hoi4_icons
description: Icon processor for Hearts of Iron IV mods.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.2

dependencies:
  CommonLib:
    git: https://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: https://github.com/FarragoFiction/LoaderLib.git
  path: any

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
